version: '3.8'

services:
  registry:
    image: registry:2
    container_name: docker-registry
    ports:
      - "5000:5000"
    volumes:
      - registry-data:/var/lib/registry
  registry-web:
    container_name: registry-ui
    image: joxit/docker-registry-ui:main
    environment:
      - NGINX_PROXY_PASS_URL=http://docker-registry:5000
      - REGISTRY_TITLE=Private Docker Registry
    ports:
      - "8080:80"
    depends_on:
      - registry
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - registry

volumes:
  registry-data:

