version: '3.8'

services:
  db:
    image: mariadb:latest
    container_name: nextcloud-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud-app
    restart: always
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: password
    volumes:
      - nextcloud_data:/var/www/html
    depends_on:
      - db
    networks:
      - nextcloud_network

  proxy:
    image: nginx:latest
    container_name: nginx-proxy
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/nginx/certs:ro
    ports:
      - 80:80
      - 443:443
    depends_on:
      - nextcloud
    networks:
      - nextcloud_network

volumes:
  db_data:
  nextcloud_data:

networks:
  nextcloud_network:

