version: "3.9"

services:
  frontend:
    image: frontend:v1
    ports:
      - "80:80" # Map frontend to port 8080 on the host
    networks:
      - app-network

  backend:
    image: backend:v1
    ports:
      - "3000:3000" # Map backend to port 3000 on the host
    depends_on:
      - database
      - cache  
    environment:
      - DATABASE_HOST=database
      - DATABASE_USER=root
      - DATABASE_PASSWORD=secret
    networks:
      - app-network

  database:
    image: database:v1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: shop
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  cache:
    image: redis:latest
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: overlay

volumes:
  db-data:

